spring:
  application:
    name: spring-service-a
server:
  # 配置服务端口
  port: 8082
eureka:
  client:
    service-url:
      # 配置eureka服务器地址
      defaultZone: http://localhost:8081/eureka/
    #是否需要将自己注册到注册中心(注册中心集群需要设置为true)
    register-with-eureka: true
    #是否需要搜索服务信息 因为自己是注册中心所以为false
    fetch-registry: true
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    #服务续约到期时间 单位秒
    lease-expiration-duration-in-seconds: 10
    #服务续约间隔时间 单位秒
    lease-renewal-interval-in-seconds: 5
